# Generated by Django 5.0.4 on 2024-04-27 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0001_initial'),
        ('video_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='video',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='video_sessions.videosession'),
            preserve_default=False,
        ),
    ]
