# Generated by Django 5.0.4 on 2024-04-27 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0002_chatmessage_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='video',
            new_name='video_id',
        ),
    ]
