# Generated by Django 5.0.4 on 2024-04-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('thumbnail_url', models.URLField()),
                ('video_url', models.URLField()),
                ('uploader_id', models.CharField(max_length=50)),
            ],
        ),
    ]
