# Generated by Django 5.0.4 on 2024-04-27 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_remove_video_uploader_id_video_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='user',
            new_name='user_id',
        ),
    ]
